on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n tddteste -g teste --location "Brazil South" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n tddteste --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n tddteste --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n tddteste --query passwords[0].value | xargs`"
    
    - uses: azure/docker-login@v1
      with:
        login-server: tddteste.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/pass" -f  "'/'" -t tddteste.azurecr.io/django5tafzy4w6gvcw-img:${{ github.sha }}
        docker push tddteste.azurecr.io/django5tafzy4w6gvcw-img:${{ github.sha }}
      
    - name: Set Web App ACR authentication
      uses: Azure/appservice-settings@v1
      with: 
        app-name: Django-5tafzy4w6gvcw
        app-settings-json: | 
          [
            {
              "name": "DOCKER_REGISTRY_SERVER_URL",
              "value": "tddteste.azurecr.io",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_USERNAME",
              "value": "${{ steps.create-acr.outputs.acr_username }}",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
              "value": "${{ steps.create-acr.outputs.acr_password }}",
              "slotSetting": false
            }
          ]
        
    - uses: azure/webapps-deploy@v2
      with:
        app-name: Django-5tafzy4w6gvcw
        images: tddteste.azurecr.io/django5tafzy4w6gvcw-img:${{ github.sha }}