
# This is a basic workflow to help you get started with Actions

name: Integração Cotínua

# Controls when the workflow will run
on:
  push:
  
jobs:
  executa_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v2
      
      - name: Instala o python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
        
      - name: Instala as dependencias
        run: |
          python -m pip install --upgrade pip
          pip3 install black 
          pip3 install isort
          pip3 install pydocstyle
          pip3 install pytest
          
      - name: executa o black
        run: black --check app
        
      - name: executa o isort
        run: isort --check app
        
      - name: Executa o  pydosctyle
        run: pydocstyle app
        
      - name: Exeutas os tests unitários
        run: pytest